### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by altruisticsoftware** [lifechurch/validstate#7]
Add [Travis CI](https://travis-ci.org/)?

**Comment by wintheday** [comment]
@MrChristofferson  I am all for getting a CI into this.  Most likely we will use Circle CI because we currently use that for our other products.  But if you have a case for Travis I am open to it. 

Also,  We are also planning on merging the docs and the library to make development easier.

**Comment by wintheday** [comment]
Travis CI added in #21  👍
